### PR TITLE
Fixed 3P/4P Ready/Set/Go indicator

### PR DESCRIPTION
**Pull request by InvisibleUp**
See last comment in #4

### CODE REVIEW

**Comment by cheatfreak47** [comment]
Uh, I hate to be the bearer of bad news- but, now single player Ready Set Go is misaligned instead?

**Comment by cheatfreak47** [comment]
@InvisibleUp 1P and H2P are now wrong, but V2P 3P, and 4P are all set no problem.

sonicr_2017-11-24_15-14-41
sonicr_2017-11-24_15-16-42

**Comment by cheatfreak47** [comment]
Results screens in multiplayer 3P/4P/V2P are also off, but 1P and H2P are fine.
sonicr_2017-11-24_15-35-48
sonicr_2017-11-24_15-38-39

**Comment by InvisibleUp** [comment]
I swear I'm actually testing these things... Thanks for checking everything, though. NOW it should hopefully all be good.

**Comment by cheatfreak47** [comment]
Tested and everything seems on point. 👍

**Pull request merged**
