### PR TITLE
Added widescreen mod to mod loader

### PR DESCRIPTION
**Pull request by InvisibleUp**
Let me know if you want anything changed. This has the updated HUD and stuff.

### CODE REVIEW

**Comment by MainMemory** [comment]
Hm, I think it would work better if it just worked with any resolution all the time, without needing to enable a separate "Widescreen" setting.

**Comment by InvisibleUp** [comment]
The only problem I know of is that in 2P mode the right player's HUD disappears when the aspect ratio is narrower than 4:3. But other than that, it should work fine.

**Comment by cheatfreak47** [comment]
@InvisibleUp All is well except for the "Ready Set Go" in multiplayer
sonicr_2017-11-24_01-34-54

As you can see, they are misaligned and P3 and probably P4 don't have them at all.
This is sweet, sonic R is now basically perfect in Single Player. Great job! 👍 :100:

**Comment by InvisibleUp** [comment]
Ah, turns out I was only checking for 2P mode when fixing the centering. Fixed now.

**Pull request merged**
